### ISSUE TITLE
initial comments on list utility

### ISSUE THREAD

**Issue by campenberger** [brisboa/ListTenants#1]
Here are some initial comments:
- is that actually working code?
- make the utility a module with a __main__.py entrypoint
- add documentation to the readme.md how to install and use the utility
- If you need any additional libraries, beside standard python you should require a freeze file, so it is to install them all with pip
- You should not access the database directly and instead only go through the rest services
- why are there all this java imports in the python script, that can't work. can it?
- clean up all the java code in the python files

**Comment by brisboa** [comment]
Code actually works.
In main.py environment.
Have requirements.txt.
Only go through REST services.
No java imports or java code in sight.

Revised README.md for installing and using utility, though I will keep updating in case some other aspect must be addressed in the README.
